server:
  port: ${APP_PORT:8080}

# Spring Config
spring:
  application:
    name: ${APP_NAME:order}
  config:
    import: optional:file:.env[.properties]

  # Datasource
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

# Application Config
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRE_MS}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRE_MS}

# Swagger UI path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Log
logging:
  level:
    com.siveing.order: ${APP_LOG_LEVEL:DEBUG}
    org.spring.framework.security: ${APP_SECURITY_LOG_LEVEL}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}%replace( [correlationId=%X{correlationId}]){' \\[correlationId=(|\\]|null)\\]', ''} - %msg%n"

