spring:
  application:
    name: order

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/boot_order_db
    username: siveing
    password: jincuteboi
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Swagger UI path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

# Log
logging:
  level:
    com.siveing.order: DEBUG
    org.spring.framework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"